[package]
name = "fotono"
version = "0.1.0"
authors = ["jack-the-coder <jack@snazz.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
